# Generated by Django 5.2 on 2025-04-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_arma_licencia_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='fecha_vencimiento_licencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
