# Generated by Django 5.2 on 2025-04-18 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_arma_fecha_vencimiento_licencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniformeAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_entrega', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('deteriorado', 'Deteriorado'), ('devuelto', 'Devuelto')], default='nuevo', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('articulo', models.ForeignKey(limit_choices_to={'categoria': 'uniforme'}, on_delete=django.db.models.deletion.CASCADE, to='operaciones.articuloinventario')),
                ('oficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.oficial')),
            ],
        ),
    ]
