# Generated by Django 5.2 on 2025-04-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_remove_uniformeasignado_observaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenciaConducir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licencia', models.CharField(max_length=20)),
                ('vencimiento', models.DateField()),
                ('archivo_licencia', models.FileField(blank=True, null=True, upload_to='licencias/supervisores/')),
                ('oficial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.oficial')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('zona', models.CharField(max_length=50)),
                ('seguro_documento', models.FileField(blank=True, null=True, upload_to='vehiculos/seguros/')),
                ('placa_documento', models.FileField(blank=True, null=True, upload_to='vehiculos/placas/')),
                ('vencimiento_seguro', models.DateField(blank=True, null=True)),
                ('vencimiento_placa', models.DateField(blank=True, null=True)),
                ('supervisor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.oficial')),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('detalle', models.TextField()),
                ('kilometraje', models.PositiveIntegerField()),
                ('archivo_factura', models.FileField(blank=True, null=True, upload_to='vehiculos/mantenimientos/')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ChequeoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('imagen_1', models.ImageField(blank=True, null=True, upload_to='vehiculos/chequeos/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='vehiculos/chequeos/')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.vehiculo')),
            ],
        ),
    ]
