# Generated by Django 5.2 on 2025-04-18 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_rename_fecha_mantenimientovehiculo_fecha_mantenimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('kilometraje_inicial', models.PositiveIntegerField()),
                ('kilometraje_final', models.PositiveIntegerField()),
                ('galones_cargados', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_por_galon', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observaciones', models.TextField(blank=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.vehiculo')),
            ],
        ),
    ]
